CREATE TABLE Info (
    Name TEXT,
    Email TEXT,
    Phone INT);

insert into Info values (Mr. Siegert, timothy.sirgert@ftcsc.org, 317-803-5660);
insert into Info values (Mrs. Jacobs, tami.jacobs@ftcsc.org, 317-803-5543);
insert into Info values (Mrs. Fledderman, rebecca.fledderman@ftcsc.org, 317-803-5642);
insert into Info values (Mrs. Levins, erin.levins@ftcsc.org, 317-803-5642);
insert into Info values (Mrs. Addison, chrsity.addison@ftcsc.org, 317-803-5540);
insert into Info values (Mr. Miller, jacob.miller@ftcsc.org, 317-803-5543);
insert into Info values (Mr. Mssey, jeffery.massey@ftcsc.org, 317-803-5575);
insert into Info values (Mrs. Ternieden, Ternieden@ftcsc.org, 317-803-5652);
insert into Info values (Mrs. Brooks, gretchen.brooks@ftcsc.org, 317-803-5545);
insert into Info values (Mrs. Flannery, ainsley.flannery@ftcsc.org, 317-803-5548);
insert into Info values (Mrs. Jinks, sharon.jinks@ftcsc.org, 317-803-5534);
insert into Info values (Ms. Northcutt, lucille.northcutt@ftcsc.org, 317-803-5544);
insert into Info values (Mrs. Lines, jansen.lines@ftcsc.org, 317-803-5694);
insert into Info values (Ms. Rockwood Weaver, kelly.Weaver@ftcsc.org, 317-803-5731);
insert into Info values (Mrs. Vonderwell, corinna.vonderwell@ftcsc.org, 317-803-5777);
insert into Info values (Mrs. Marquez, maria.marquez@ftcsc.org, 317-803-8302);
insert into Info values (Mrs. Welling, heather.welling@ftcsc.org, 317-803-5615);

